[package]
name = "suora"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
sha2 = "0.10.8"
url = "2.5.4"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
strip = "debuginfo"
