package main

import (
	"encoding/json"
	"fmt"
	"runtime"
	"strings"
	"sync"
	"testing"
	"time"
)

// Generated by the rules target in the Makefile; run `make rules` before `go test`.
const (
	compiledRulesPath = "build/rules.json"
	rulesTestsPath    = "build/rules.tests.json"
)

func TestExtractionRules(t *testing.T) {
	if err := LoadRules(mustReadConfig(compiledRulesPath)); err != nil {
		t.Fatalf("Failed to load config: %v", err)
	}

	// The compiled rules carry no test blocks -- cmd/rules-compile splits them
	// into a sidecar that reuses the same document shape, keyed by domain.
	var cases Config
	if err := json.Unmarshal(mustReadConfig(rulesTestsPath), &cases); err != nil {
		t.Fatalf("Failed to parse %s: %v", rulesTestsPath, err)
	}

	for _, site := range cases.Sites {
		for _, test := range site.Tests {
			t.Run(fmt.Sprintf("%s/%s", site.Domain, test.Url), func(t *testing.T) {
				var hashed = ""

				resUrl, matched, err := matchURL("", test.Url)

				// An xfail case is not a gap in the rules: it says the URL is not an article, so no named
				// rule may match it. The catch-all resolves it instead, which is what is checked here. A
				// named rule that starts matching a listing page fails this.
				if test.XFail {
					if err != nil {
						t.Fatalf("❌ Expected the catch-all to resolve: %s\nError: %v\n\n", test.Url, err)
					}
					if matched.Domain != "" {
						t.Fatalf("❌ Expected no named rule to match: %s\nMatched domain: %s\nGot: %s\n\n",
							test.Url, matched.Domain, resUrl)
					}
					t.Logf("✅ No named rule matches, the catch-all resolved: %s\n", test.Url)
					return
				}

				if test.Signature != "" {
					hashed = generateSignature(resUrl)
				} else {
					t.Logf("⚠️ No signature to test for: %s\n", test.Url)
				}
				if err != nil || resUrl != test.Expected {
					t.Fatalf("❌ Test failed for: %s\nExpected: %s\nGot: %s\nError: %v\n\n",
						test.Url, test.Expected, resUrl, err)
				} else {
					if hashed != "" && hashed != test.Signature {
						t.Fatalf("❌ Signature mismatch for: %s\nExpected: %s\nGot: %s\n\n",
							test.Url, test.Signature, hashed)
					} else {
						t.Logf("✅ Test passed for: %s\n", test.Url)
					}
				}
			})
		}
	}
}

func TestWildcardAndDomainMatching(t *testing.T) {
	customRules := []byte(`{"sites": [
  {"domain": "example.com", "templates": [
    {"pattern": "^/article/(?P<ArticleID>[^/]+)", "template": "https://example.com/article/{{ .ArticleID }}"}
  ]},
  {"domain": "example.com:8443", "templates": [
    {"pattern": "^/port-article/(?P<ID>[^/]+)", "template": "https://example.com:8443/port-article/{{ .ID }}"}
  ]},
  {"domain": "", "templates": [
    {"template": "{{ .URL }}"}
  ]}
]}`)

	err := LoadRules(customRules)
	if err != nil {
		t.Fatalf("Failed to load custom rules: %v", err)
	}

	tests := []struct {
		name     string
		inputURL string
		expected string
	}{
		{
			name:     "Exact domain match",
			inputURL: "https://example.com/article/123",
			expected: "https://example.com/article/123",
		},
		{
			name:     "Subdomain match for example.com",
			inputURL: "https://www.example.com/article/123",
			expected: "https://example.com/article/123",
		},
		{
			name:     "Default HTTPS port 443 normalizes and matches example.com",
			inputURL: "https://www.example.com:443/article/123",
			expected: "https://example.com/article/123",
		},
		{
			name:     "Non-subdomain suffix wwwexample.com falls through to wildcard rule",
			inputURL: "https://wwwexample.com/article/123",
			expected: "https://wwwexample.com/article/123",
		},
		{
			name:     "Non-default port 8443 matches explicit host:port rule",
			inputURL: "https://example.com:8443/port-article/999",
			expected: "https://example.com:8443/port-article/999",
		},
		{
			name:     "Non-default port 8080 falls through to wildcard rule",
			inputURL: "https://example.com:8080/article/123",
			expected: "https://example.com:8080/article/123",
		},
		{
			name:     "Wildcard domain rule uses implicit .URL field",
			inputURL: "https://randomsite.org/path/to/page?b=2&a=1",
			expected: "https://randomsite.org/path/to/page?a=1&b=2",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			res, err := processURL(tt.inputURL)
			if err != nil {
				t.Fatalf("processURL unexpected error: %v", err)
			}
			if res != tt.expected {
				t.Errorf("Expected %s, got %s", tt.expected, res)
			}
		})
	}
}

// The wildcard rule matches every host, so an input with no host must be refused before matching, or it signs.
func TestURLWithoutHostIsRefused(t *testing.T) {
	freshBase(t, `{"sites": [{"domain": "", "templates": [{"template": "{{ .URL }}"}]}]}`)

	for _, inputURL := range []string{
		"mailto:someone@example.com",
		"about:blank",
		"/relative/path",
		"https:///path",
		"https://:8080/path", // A port without a host: Host is ":8080", Hostname is empty.
	} {
		if res, err := processURL(inputURL); err == nil {
			t.Errorf("processURL(%q) = %q, expected an error for a URL with no host", inputURL, res)
		}
	}
}

func TestSiteWeightCalculation(t *testing.T) {
	// Rules defining catch-all first, then com, example.com, www.example.com, and an explicit weight override.
	customRules := []byte(`{"sites": [
  {"domain": "", "templates": [
    {"template": "https://catch-all.org{{ .Path }}"}
  ]},
  {"domain": "com", "templates": [
    {"pattern": "^/tld/(?P<ID>[^/]+)", "template": "https://tld.com/{{ .ID }}"}
  ]},
  {"domain": "example.com", "templates": [
    {"pattern": "^/fallback-only/(?P<ID>[^/]+)", "template": "https://example.com/fallback/{{ .ID }}"},
    {"pattern": "^/article/(?P<ID>[^/]+)", "template": "https://example.com/article/{{ .ID }}"}
  ]},
  {"domain": "www.example.com", "templates": [
    {"pattern": "^/article/(?P<ID>[^/]+)", "template": "https://www.example.com/subdomain/article/{{ .ID }}"}
  ]},
  {"domain": "override.com", "weight": 2000, "templates": [
    {"pattern": "^/article/(?P<ID>[^/]+)", "template": "https://override.com/high-priority/{{ .ID }}"}
  ]}
]}`)

	err := LoadRules(customRules)
	if err != nil {
		t.Fatalf("Failed to load custom rules: %v", err)
	}

	// Verify weights computed correctly
	// override.com -> explicit 2000
	// www.example.com -> 100 + 15 = 115
	// example.com -> 100 + 11 = 111
	// com -> 100 + 3 = 103
	// "" -> 0
	expectedDomainOrder := []string{"override.com", "www.example.com", "example.com", "com", ""}
	cfg := GetRules()
	if len(cfg.Sites) != len(expectedDomainOrder) {
		t.Fatalf("Expected %d sites, got %d", len(expectedDomainOrder), len(cfg.Sites))
	}
	for i, expectedDom := range expectedDomainOrder {
		if cfg.Sites[i].Domain != expectedDom {
			t.Errorf("Site index %d: expected domain %q, got %q", i, expectedDom, cfg.Sites[i].Domain)
		}
	}

	tests := []struct {
		name     string
		inputURL string
		expected string
	}{
		{
			name:     "Explicit weight override takes top priority",
			inputURL: "https://www.override.com/article/1",
			expected: "https://override.com/high-priority/1",
		},
		{
			name:     "www.example.com (weight 115) matches before example.com (weight 111)",
			inputURL: "https://www.example.com/article/123",
			expected: "https://www.example.com/subdomain/article/123",
		},
		{
			name:     "Falls through www.example.com to example.com if path pattern doesn't match www rule",
			inputURL: "https://www.example.com/fallback-only/456",
			expected: "https://example.com/fallback/456",
		},
		{
			name:     "Falls through example.com to com if path pattern matches TLD rule",
			inputURL: "https://www.example.com/tld/789",
			expected: "https://tld.com/789",
		},
		{
			name:     "Falls through to catch-all if no specific domain/path matches",
			inputURL: "https://www.example.com/unknown/path",
			expected: "https://catch-all.org/unknown/path",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			res, err := processURL(tt.inputURL)
			if err != nil {
				t.Fatalf("processURL unexpected error: %v", err)
			}
			if res != tt.expected {
				t.Errorf("Expected %s, got %s", tt.expected, res)
			}
		})
	}
}

func TestRulesPayloadLimits(t *testing.T) {
	// Empty data should fail
	if err := LoadRules([]byte("")); err == nil {
		t.Errorf("Expected error for empty rules data")
	}

	// Data exceeding MaxRulesSize (2MB) should fail
	oversized := make([]byte, MaxRulesSize+1)
	for i := range oversized {
		oversized[i] = ' '
	}
	if err := LoadRules(oversized); err == nil {
		t.Errorf("Expected error for oversized rules data")
	}

	// Oversized regex pattern should fail
	oversizedPattern := strings.Repeat("a", MaxPatternLength+1)
	rules := fmt.Sprintf(`{"sites": [
  {"domain": "limit.com", "templates": [
    {"pattern": %q, "template": "https://limit.com/{{ .URL }}"}
  ]}
]}`, oversizedPattern)
	if err := LoadRules([]byte(rules)); err == nil {
		t.Errorf("Expected error for oversized regex pattern")
	}
}

func TestAppendRules(t *testing.T) {
	initialRules := []byte(`{"sites": [
  {"domain": "base.com", "templates": [
    {"pattern": "^/item/(?P<ID>[^/]+)", "template": "https://base.com/item/{{ .ID }}"}
  ]}
]}`)

	additionalRules := []byte(`{"sites": [
  {"domain": "appended.com", "templates": [
    {"pattern": "^/page/(?P<ID>[^/]+)", "template": "https://appended.com/page/{{ .ID }}"}
  ]}
]}`)

	if err := LoadRules(initialRules); err != nil {
		t.Fatalf("LoadRules failed: %v", err)
	}

	res, err := processURL("https://base.com/item/1")
	if err != nil || res != "https://base.com/item/1" {
		t.Fatalf("Base rule failed: got %s, err %v", res, err)
	}

	if err := AppendRules(additionalRules); err != nil {
		t.Fatalf("AppendRules failed: %v", err)
	}

	// Verify base rule still works
	res, err = processURL("https://base.com/item/1")
	if err != nil || res != "https://base.com/item/1" {
		t.Fatalf("Base rule after append failed: got %s, err %v", res, err)
	}

	// Verify appended rule works
	res, err = processURL("https://appended.com/page/42")
	if err != nil || res != "https://appended.com/page/42" {
		t.Fatalf("Appended rule failed: got %s, err %v", res, err)
	}
}

func TestDomainCollisionPriority(t *testing.T) {
	initialRules := []byte(`{"sites": [
  {"domain": "collision.com", "templates": [
    {"pattern": "^/article/(?P<ID>[^/]+)", "template": "https://collision.com/original/{{ .ID }}"}
  ]}
]}`)

	// Appending rule for collision.com with same default weight (fallback)
	equalWeightAppendedRules := []byte(`{"sites": [
  {"domain": "collision.com", "templates": [
    {"pattern": "^/article/(?P<ID>[^/]+)", "template": "https://collision.com/equal-appended/{{ .ID }}"},
    {"pattern": "^/new-feature/(?P<ID>[^/]+)", "template": "https://collision.com/new-feature/{{ .ID }}"}
  ]}
]}`)

	if err := LoadRules(initialRules); err != nil {
		t.Fatalf("LoadRules failed: %v", err)
	}

	if err := AppendRules(equalWeightAppendedRules); err != nil {
		t.Fatalf("AppendRules failed: %v", err)
	}

	// Original rule should evaluate first for /article/
	res, err := processURL("https://collision.com/article/100")
	if err != nil || res != "https://collision.com/original/100" {
		t.Fatalf("Expected original rule precedence for /article/, got %s, err %v", res, err)
	}

	// New feature path should fall through to appended rule
	res, err = processURL("https://collision.com/new-feature/200")
	if err != nil || res != "https://collision.com/new-feature/200" {
		t.Fatalf("Expected fallthrough to appended rule for /new-feature/, got %s, err %v", res, err)
	}

	// Now append a high-weight override rule
	overrideRules := []byte(`{"sites": [
  {"domain": "collision.com", "weight": 9999, "templates": [
    {"pattern": "^/article/(?P<ID>[^/]+)", "template": "https://collision.com/override/{{ .ID }}"}
  ]}
]}`)

	if err := AppendRules(overrideRules); err != nil {
		t.Fatalf("AppendRules override failed: %v", err)
	}

	// High-weight override rule must take top priority for /article/
	res, err = processURL("https://collision.com/article/100")
	if err != nil || res != "https://collision.com/override/100" {
		t.Fatalf("Expected high-weight override rule precedence for /article/, got %s, err %v", res, err)
	}
}

func TestAppendSortingDeterminism(t *testing.T) {
	ruleA := `{"sites": [
  {"domain": "aaa.com", "templates": [{"template": "https://aaa.com{{ .Path }}"}]}
]}`
	ruleB := `{"sites": [
  {"domain": "bbb.com", "templates": [{"template": "https://bbb.com{{ .Path }}"}]}
]}`

	// Sequence 1: Load A, Append B
	if err := LoadRules([]byte(ruleA)); err != nil {
		t.Fatalf("LoadRules A failed: %v", err)
	}
	if err := AppendRules([]byte(ruleB)); err != nil {
		t.Fatalf("AppendRules B failed: %v", err)
	}
	cfg1 := GetRules()
	domains1 := []string{cfg1.Sites[0].Domain, cfg1.Sites[1].Domain}

	// Sequence 2: Load B, Append A
	if err := LoadRules([]byte(ruleB)); err != nil {
		t.Fatalf("LoadRules B failed: %v", err)
	}
	if err := AppendRules([]byte(ruleA)); err != nil {
		t.Fatalf("AppendRules A failed: %v", err)
	}
	cfg2 := GetRules()
	domains2 := []string{cfg2.Sites[0].Domain, cfg2.Sites[1].Domain}

	if domains1[0] != domains2[0] || domains1[1] != domains2[1] {
		t.Fatalf("Sorting non-deterministic across appends: seq1 %v vs seq2 %v", domains1, domains2)
	}
}

func TestConcurrentReadAndAppend(t *testing.T) {
	concurrentRules := []byte(`{"sites": [
  {"domain": "concurrent.com", "templates": [
    {"pattern": "^/item/(?P<ID>[^/]+)", "template": "https://concurrent.com/item/{{ .ID }}"}
  ]}
]}`)
	if err := LoadRules(concurrentRules); err != nil {
		t.Fatalf("LoadRules failed: %v", err)
	}

	stopChan := make(chan struct{})
	var wg sync.WaitGroup

	// Launch 50 reader goroutines
	for i := 0; i < 50; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for {
				select {
				case <-stopChan:
					return
				default:
					res, err := processURL("https://concurrent.com/item/99")
					if err != nil || res != "https://concurrent.com/item/99" {
						t.Errorf("Concurrent reader failed: got %s, err %v", res, err)
						return
					}
					// This loop never blocks, so on a cooperative scheduler --
					// TinyGo on single-threaded wasm -- the first reader would
					// spin forever and nothing else would ever run. Yielding
					// costs nothing natively and lets the test run on both.
					runtime.Gosched()
				}
			}
		}()
	}

	// Launch 5 writer goroutines appending rules
	for i := 0; i < 5; i++ {
		wg.Add(1)
		go func(workerID int) {
			defer wg.Done()
			rules := fmt.Sprintf(`{"sites": [
  {"domain": "worker%d.com", "templates": [
    {"pattern": "^/page/(?P<ID>[^/]+)", "template": "https://worker%d.com/page/{{ .ID }}"}
  ]}
]}`, workerID, workerID)
			for j := 0; j < 10; j++ {
				_ = AppendRules([]byte(rules))
			}
		}(i)
	}

	// Allow writers to finish
	time.Sleep(50 * time.Millisecond)
	close(stopChan)
	wg.Wait()
}

// Rule sets for the layering tests. Both name hs.fi, so both get the same derived weight and the order of
// the layers is the only thing that can decide which template runs first.
const (
	layerBaseRules = `{"sites": [
  {"domain": "hs.fi", "templates": [
    {"pattern": "^/a/(?P<ID>[^/]+)", "template": "https://hs.fi/base-a/{{ .ID }}"},
    {"pattern": "^/b/(?P<ID>[^/]+)", "template": "https://hs.fi/base-b/{{ .ID }}"}
  ]}
]}`
	layerOwnerRules = `{"sites": [
  {"domain": "hs.fi", "templates": [
    {"pattern": "^/a/(?P<ID>[^/]+)", "template": "https://hs.fi/owner-a/{{ .ID }}"}
  ]}
]}`
)

func mustLoad(t *testing.T, data string) {
	t.Helper()
	if err := LoadRules([]byte(data)); err != nil {
		t.Fatalf("LoadRules failed: %v", err)
	}
}

// freshBase clears the rule set registry and loads base rules. The registry is package state that outlives
// a test, so a test that counts or names rule sets has to start from a known one.
func freshBase(t *testing.T, data string) {
	t.Helper()
	for _, name := range RuleSetNames() {
		if err := DropRules(name); err != nil {
			t.Fatalf("DropRules(%q) failed: %v", name, err)
		}
	}
	mustLoad(t, data)
}

func mustDefine(t *testing.T, name, data string) {
	t.Helper()
	if err := DefineRules(name, []byte(data)); err != nil {
		t.Fatalf("DefineRules(%q) failed: %v", name, err)
	}
}

// mustSignIn checks the URL against the named rule set. An empty name is the base rules.
func mustSignIn(t *testing.T, name, inputURL, expected string) {
	t.Helper()
	res, _, err := matchURL(name, inputURL)
	if err != nil {
		t.Fatalf("matchURL(%q, %s) failed: %v", name, inputURL, err)
	}
	if res != expected {
		t.Errorf("matchURL(%q, %s) = %s, expected %s", name, inputURL, res, expected)
	}
}

func mustProcess(t *testing.T, inputURL, expected string) {
	t.Helper()
	mustSignIn(t, "", inputURL, expected)
}

func TestDefinedRuleSetLayersOverTheBase(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:hs.fi", layerOwnerRules)

	// Same domain and same derived weight: the layer site is first in the composed set, so it wins.
	mustSignIn(t, "owner:hs.fi", "https://hs.fi/a/1", "https://hs.fi/owner-a/1")
	// The base site stays in the set below the layer and catches the paths the layer does not match.
	mustSignIn(t, "owner:hs.fi", "https://hs.fi/b/2", "https://hs.fi/base-b/2")
	// Naming no rule set is the base rules, which the definition did not change.
	mustProcess(t, "https://hs.fi/a/1", "https://hs.fi/base-a/1")
}

// Naming a rule set at the point of use is the whole design: no call can put the module into a mode that a
// later call reads by accident, so signing in two sets cannot interfere.
func TestRuleSetsDoNotInterfere(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:a", layerOwnerRules)
	mustDefine(t, "owner:b", `{"sites": [
  {"domain": "hs.fi", "templates": [
    {"pattern": "^/a/(?P<ID>[^/]+)", "template": "https://hs.fi/other-a/{{ .ID }}"}
  ]}
]}`)

	for range 3 {
		mustSignIn(t, "owner:a", "https://hs.fi/a/1", "https://hs.fi/owner-a/1")
		mustSignIn(t, "owner:b", "https://hs.fi/a/1", "https://hs.fi/other-a/1")
		mustProcess(t, "https://hs.fi/a/1", "https://hs.fi/base-a/1")
	}
}

func TestDefineRulesReplacesAName(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:hs.fi", layerOwnerRules)
	mustDefine(t, "owner:hs.fi", `{"sites": [
  {"domain": "hs.fi", "templates": [
    {"pattern": "^/a/(?P<ID>[^/]+)", "template": "https://hs.fi/replaced-a/{{ .ID }}"}
  ]}
]}`)

	mustSignIn(t, "owner:hs.fi", "https://hs.fi/a/1", "https://hs.fi/replaced-a/1")
	if names := RuleSetNames(); len(names) != 1 {
		t.Errorf("Expected 1 rule set after a replacement, got %v", names)
	}
}

// An unknown name is reported. Falling back to the base rules would sign a URL against rules the caller did
// not ask for, and the signature would not say so.
func TestUnknownRuleSetIsReported(t *testing.T) {
	freshBase(t, layerBaseRules)

	if _, err := getSignatureIn("owner:missing", "https://hs.fi/a/1"); err == nil {
		t.Error("Expected an error for an unknown rule set")
	}
	if err := DropRules("owner:missing"); err == nil {
		t.Error("Expected an error when dropping an unknown rule set")
	}
}

func TestDropRules(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:hs.fi", layerOwnerRules)

	if err := DropRules("owner:hs.fi"); err != nil {
		t.Fatalf("DropRules failed: %v", err)
	}
	if _, err := getSignatureIn("owner:hs.fi", "https://hs.fi/a/1"); err == nil {
		t.Error("Expected the dropped rule set to be gone")
	}
	// Dropping a layer leaves the base rules alone.
	mustProcess(t, "https://hs.fi/a/1", "https://hs.fi/base-a/1")
}

func TestRuleSetNames(t *testing.T) {
	freshBase(t, layerBaseRules)
	for _, name := range []string{"owner:c", "owner:a", "owner:b"} {
		mustDefine(t, name, layerOwnerRules)
	}

	got := RuleSetNames()
	want := []string{"owner:a", "owner:b", "owner:c"}
	if len(got) != len(want) {
		t.Fatalf("Expected %v, got %v", want, got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("Expected %v, got %v", want, got)
			break
		}
	}

	for _, name := range want {
		if err := DropRules(name); err != nil {
			t.Fatalf("DropRules(%q) failed: %v", name, err)
		}
	}
	if names := RuleSetNames(); len(names) != 0 {
		t.Errorf("Expected no rule sets, got %v", names)
	}
}

func TestDefineRulesAtomicOnFailure(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:hs.fi", layerOwnerRules)

	if err := DefineRules("owner:hs.fi", []byte(`{"sites": "this is not a list of sites"}`)); err == nil {
		t.Fatal("Expected an error for an invalid rule set")
	}
	mustSignIn(t, "owner:hs.fi", "https://hs.fi/a/1", "https://hs.fi/owner-a/1")

	badPattern := fmt.Sprintf(`{"sites": [{"domain": "hs.fi", "templates": [
  {"pattern": %q, "template": "https://hs.fi/bad/{{ .ID }}"}
]}]}`, strings.Repeat("a", MaxPatternLength+1))
	if err := DefineRules("owner:hs.fi", []byte(badPattern)); err == nil {
		t.Fatal("Expected an error for a rule set that does not compile")
	}
	mustSignIn(t, "owner:hs.fi", "https://hs.fi/a/1", "https://hs.fi/owner-a/1")

	if err := DefineRules("", []byte(layerOwnerRules)); err == nil {
		t.Error("Expected an error for an empty rule set name")
	}
}

// A named set means "this layer over the base rules". If the base moves and the set does not, it keeps
// layering over rules that are no longer active, and nothing says so.
func TestNamedSetsFollowTheBaseRules(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:hs.fi", layerOwnerRules)
	mustSignIn(t, "owner:hs.fi", "https://hs.fi/b/2", "https://hs.fi/base-b/2")

	// LoadRules replaces the base.
	mustLoad(t, `{"sites": [
  {"domain": "hs.fi", "templates": [
    {"pattern": "^/a/(?P<ID>[^/]+)", "template": "https://hs.fi/new-a/{{ .ID }}"},
    {"pattern": "^/b/(?P<ID>[^/]+)", "template": "https://hs.fi/new-b/{{ .ID }}"}
  ]}
]}`)
	mustSignIn(t, "owner:hs.fi", "https://hs.fi/a/1", "https://hs.fi/owner-a/1")
	mustSignIn(t, "owner:hs.fi", "https://hs.fi/b/2", "https://hs.fi/new-b/2")

	// AppendRules grows the base.
	if err := AppendRules([]byte(`{"sites": [
  {"domain": "appended.example", "templates": [
    {"pattern": "^/page/(?P<ID>[^/]+)", "template": "https://appended.example/page/{{ .ID }}"}
  ]}
]}`)); err != nil {
		t.Fatalf("AppendRules failed: %v", err)
	}
	mustSignIn(t, "owner:hs.fi", "https://appended.example/page/1", "https://appended.example/page/1")
}

// The mirror of TestDomainCollisionPriority: there an appended rule of equal weight does not displace the
// loaded one, here a layer of equal weight does displace it.
func TestLayerWinsEqualWeight(t *testing.T) {
	base, err := parseAndCompile([]byte(layerBaseRules))
	if err != nil {
		t.Fatalf("parseAndCompile failed: %v", err)
	}
	layer, err := parseAndCompile([]byte(layerOwnerRules))
	if err != nil {
		t.Fatalf("parseAndCompile failed: %v", err)
	}

	composed := layerOver(layer, base)
	if len(composed.Sites) != 2 {
		t.Fatalf("Expected 2 sites, got %d", len(composed.Sites))
	}
	if composed.Sites[0]._EffectiveWeight != composed.Sites[1]._EffectiveWeight {
		t.Fatalf("Test needs equal weights, got %d and %d",
			composed.Sites[0]._EffectiveWeight, composed.Sites[1]._EffectiveWeight)
	}
	if got := composed.Sites[0].Templates[0].Template; got != "https://hs.fi/owner-a/{{ .ID }}" {
		t.Errorf("Expected the layer to sort first, got %s", got)
	}
}

// An owner can reach every host routed to it: a catch-all with an explicit weight outranks a named rule.
func TestWildcardWithExplicitWeightOutranksNamedRule(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:hs.fi", `{"sites": [
  {"domain": "", "weight": 9999, "templates": [
    {"template": "https://owner.example{{ .Path }}"}
  ]}
]}`)

	mustSignIn(t, "owner:hs.fi", "https://hs.fi/a/1", "https://owner.example/a/1")
	mustSignIn(t, "owner:hs.fi", "https://anything.example/x", "https://owner.example/x")
	// The base rules are untouched, which is what naming the set at the point of use buys.
	mustProcess(t, "https://hs.fi/a/1", "https://hs.fi/base-a/1")
}

// Weight is not clamped: an explicit value replaces 100 + len(domain) as given, in both directions.
func TestExplicitWeightIsNotClamped(t *testing.T) {
	freshBase(t, `{"sites": [
  {"domain": "low.example", "weight": -5, "templates": [{"template": "https://low.example{{ .Path }}"}]},
  {"domain": "", "weight": 1000000, "templates": [{"template": "https://high.example{{ .Path }}"}]}
]}`)

	cfg := GetRules()
	if cfg.Sites[0]._EffectiveWeight != 1000000 || cfg.Sites[1]._EffectiveWeight != -5 {
		t.Fatalf("Expected weights 1000000 then -5, got %d then %d",
			cfg.Sites[0]._EffectiveWeight, cfg.Sites[1]._EffectiveWeight)
	}
	mustProcess(t, "https://low.example/x", "https://high.example/x")
}

func TestConcurrentHashAcrossRuleSets(t *testing.T) {
	freshBase(t, layerBaseRules)
	mustDefine(t, "owner:hs.fi", layerOwnerRules)

	stopChan := make(chan struct{})
	var wg sync.WaitGroup

	// Each reader names its rule set, so every reader has one correct answer whatever the writers do.
	for i := range 50 {
		wg.Add(1)
		go func(readerID int) {
			defer wg.Done()
			name, expected := "", "https://hs.fi/base-a/1"
			if readerID%2 == 0 {
				name, expected = "owner:hs.fi", "https://hs.fi/owner-a/1"
			}
			for {
				select {
				case <-stopChan:
					return
				default:
					res, _, err := matchURL(name, "https://hs.fi/a/1")
					if err != nil || res != expected {
						t.Errorf("Concurrent reader failed: got %s, err %v", res, err)
						return
					}
					// See the note in TestConcurrentReadAndAppend: this loop never blocks, so a
					// cooperative scheduler needs the yield.
					runtime.Gosched()
				}
			}
		}(i)
	}

	// Writers churn the registry and the base underneath the readers.
	for i := range 5 {
		wg.Add(1)
		go func(workerID int) {
			defer wg.Done()
			name := fmt.Sprintf("churn:%d", workerID)
			for range 10 {
				_ = DefineRules(name, []byte(layerOwnerRules))
				_ = LoadRules([]byte(layerBaseRules))
				_ = DropRules(name)
			}
		}(i)
	}

	time.Sleep(50 * time.Millisecond)
	close(stopChan)
	wg.Wait()
}

// The registry is replaced whole on every write, so two writers that clone it at the same time would both
// store a map missing the other's change. The race detector cannot see that -- every access goes through
// the atomic pointer -- so the lost update is what this test looks for.
func TestConcurrentDefineKeepsEveryRuleSet(t *testing.T) {
	freshBase(t, layerBaseRules)

	const writers = 20
	var wg sync.WaitGroup
	for i := range writers {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			if err := DefineRules(fmt.Sprintf("owner:%d", id), []byte(layerOwnerRules)); err != nil {
				t.Errorf("DefineRules failed: %v", err)
			}
		}(i)
	}
	wg.Wait()

	if names := RuleSetNames(); len(names) != writers {
		t.Errorf("Expected %d rule sets after concurrent defines, got %d: %v", writers, len(names), names)
	}
}
