name: "Build and Test"

# Details about the workflow:
# - `Dockerfile` uses multi-stage builds to create build and test stages.
# - Builds both browser and WASI Wasm modules and uploads them as artifacts.
# - Builds a Python wheel from wasi build and uploads it as an artifact.
# - Runs Go and Python tests in a containerized environment.

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

  pull_request:
    branches: 
     - '**'

permissions:
  contents: read
  actions: read  # required for uploading artifacts

jobs:
  build:
    name: "🛠️ Build Modules"
    runs-on: ubuntu-latest

    steps:
      - name: "🔄 Checkout code"
        uses: actions/checkout@v4

      - name: "🔧 Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3


      - name: "🏗️ Build wasm modules (in Docker container)"
        run: |
          docker build --target wasm-builder -t wasm-builder .
          # Run the build entrypoint inside the container
          docker run --rm \
            -v ${{ github.workspace }}/build:/app/build \
            wasm-builder

      - name: "🏗️ Build python wheel (in Docker container)"
        run: |
          docker build --target python-builder -t python-builder .
          # Run the build entrypoint inside the container
          docker run --rm \
            -v ${{ github.workspace }}/build:/app/build \
            python-builder

      - name: "🧪 Run Go tests (in Docker container)"
        run: |
          docker build --target test -t test-runner .
          docker run --rm \
            -v ${{ github.workspace }}/build:/app/build \
            test-runner

      - name: "🧪 Run Python tests (in Docker container)"
        run: |
          docker build --target python-test -t python-test-runner .
          docker run --rm \
            -v ${{ github.workspace }}/build:/app/build \
            python-test-runner

      # TODO: run test-wasi, but requires fixing the wasi tests first
      # - name: "🧪 Run WASI tests (in Docker container)"
      #   run: ...

      - name: "⬆️ Upload artifacts"
        # Upload the build artifacts to the GitHub Actions workspace
        # This is useful for testing
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/suola-*.whl
            build/*.wasm
            build/wasm_exec.js
